In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
hdfc=pd.read_csv('/kaggle/input/data-historical/HDFCBANK.NS_MAX_NSE.csv')

In [3]:
hdfc.head()

                        date  close  open  high   low     volume
0  1995-06-15T00:00:00+05:30   2.27  2.30  2.30  2.25  2070000.0
1  1995-06-16T00:00:00+05:30   2.26  2.28  2.31  2.25  4246000.0
2  1995-06-19T00:00:00+05:30   2.26  2.26  2.27  2.22  1798000.0
3  1995-06-20T00:00:00+05:30   2.25  2.26  2.26  2.24  2792000.0
4  1995-06-21T00:00:00+05:30   2.27  2.33  2.33  2.27  1182000.0

In [4]:
hdfc.tail(5)

                           date   close     open     high    low      volume
7880  2026-01-05T00:00:00+05:30  977.50  1005.75  1006.40  976.3  27647379.0
7881  2026-01-06T00:00:00+05:30  962.20   962.70   966.70  956.0  31988783.0
7882  2026-01-07T00:00:00+05:30  949.05   956.00   956.45  946.0  52884712.0
7883  2026-01-08T00:00:00+05:30  946.70   944.70   953.00  941.4  21928849.0
7884  2026-01-09T00:00:00+05:30  939.00   945.00   950.60  933.3  38183685.0

In [5]:
bsens=pd.read_csv('/kaggle/input/historical-data/BSESN_Max.csv')
bsens.head(5)

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
0,2003-07-14 00:00:00+05:30,3704.629883,3726.560059,3704.629883,3720.750000,3720.750000,21200,0.0,0.0
1,2003-07-15 00:00:00+05:30,3719.169922,3733.879883,3657.179932,3686.340088,3686.340088,22800,0.0,0.0
2,2003-07-16 00:00:00+05:30,3702.139893,3729.020020,3662.699951,3721.649902,3721.649902,18400,0.0,0.0
3,2003-07-17 00:00:00+05:30,3728.840088,3750.000000,3660.340088,3668.909912,3668.909912,22000,0.0,0.0
4,2003-07-18 00:00:00+05:30,3651.389893,3684.229980,3625.729980,3647.580078,3647.580078,22000,0.0,0.0

In [6]:
bsens.tail(5)

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
5526,2026-01-05 00:00:00+05:30,85640.046875,85883.500000,85315.328125,85439.617188,85439.617188,12600,0.0,0.0
5527,2026-01-06 00:00:00+05:30,85331.140625,85397.781250,84900.101562,85063.343750,85063.343750,23300,0.0,0.0
5528,2026-01-07 00:00:00+05:30,84620.398438,85075.992188,84617.492188,84961.140625,84961.140625,19200,0.0,0.0
5529,2026-01-08 00:00:00+05:30,84778.023438,84965.273438,84110.101562,84180.960938,84180.960938,26300,0.0,0.0
5530,2026-01-09 00:00:00+05:30,84022.093750,84406.218750,83402.281250,83576.242188,83576.242188,12500,0.0,0.0

In [7]:
import glob
import os

files_to_change_data=glob.glob('/kaggle/input/historical-data/*')

for i in files_to_change_data:
    df=pd.read_csv(i)
    print(i)
    cols_to_drop=['Dividends','Stock Splits']
    existing_cols=[j for j in cols_to_drop if j in df.columns]

    if existing_cols:
        df.drop(columns=cols_to_drop,inplace=True)
    print(df.columns)
    print(df.shape)

    df.dropna(inplace=True)
    print(df.shape)
    
    if 'Date' in df.columns:
        df['Date']=pd.to_datetime(df['Date'],utc=True)
        df['Date']=df['Date'].dt.date
        
    filename = os.path.basename(i)
    save_path = f"/kaggle/working/Cleaned_{filename}"
    
    df.to_csv(save_path, index=False)

/kaggle/input/historical-data/GSPC_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(19126, 7)
(19126, 7)
/kaggle/input/historical-data/IXIC_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(10392, 7)
(10392, 7)
/kaggle/input/historical-data/RELIANCE.NS_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(7421, 7)
(7421, 7)
/kaggle/input/historical-data/RUT_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(9654, 7)
(9654, 7)
/kaggle/input/historical-data/NSEI_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(3161, 7)
(3161, 7)
/kaggle/input/historical-data/BSESN_Max.csv
Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')
(5531, 7)
(5531, 7)

In [8]:
files_to_see=glob.glob('/kaggle/working/*.csv')

for i in files_to_see:
    df=pd.read_csv(i)
    print(i)
    print(df.head(5))
    print('\n')
    print(df.tail(5))
    print('\n')
    print('\n')

/kaggle/working/Cleaned_NSEI_Max.csv
         Date         Open         High          Low        Close  \
0  2013-01-20  6085.750000  6094.350098  6065.100098  6082.299805
1  2013-01-21  6080.149902  6101.299805  6040.500000  6048.500000
2  2013-01-22  6052.850098  6069.799805  6021.149902  6054.299805
3  2013-01-23  6046.200195  6065.299805  6007.850098  6019.350098
4  2013-01-24  6024.500000  6080.549805  6014.450195  6074.649902

     Adj Close  Volume
0  6082.299805  130900
1  6048.500000  129000
2  6054.299805  137000
3  6019.350098  185200
4  6074.649902  147600


            Date          Open          High           Low         Close  \
3156  2026-01-04  26333.699219  26373.199219  26210.050781  26250.300781
3157  2026-01-05  26189.699219  26273.949219  26124.750000  26178.699219
3158  2026-01-06  26143.099609  26187.150391  26067.900391  26140.750000
3159  2026-01-07  26106.500000  26133.199219  25858.449219  25876.849609
3160  2026-01-08  25840.400391  25940.599609  25623.000000  25683.300781

         Adj Close  Volume
3156  26250.300781  338800
3157  26178.699219  383000
3158  26140.750000  338200
3159  25876.849609  328500
3160  25683.300781  348800




/kaggle/working/Cleaned_GSPC_Max.csv
         Date   Open   High    Low  Close  Adj Close   Volume
0  1950-01-03  16.66  16.66  16.66  16.66      16.66  1260000
1  1950-01-04  16.85  16.85  16.85  16.85      16.85  1890000
2  1950-01-05  16.93  16.93  16.93  16.93      16.93  2550000
3  1950-01-06  16.98  16.98  16.98  16.98      16.98  2010000
4  1950-01-09  17.08  17.08  17.08  17.08      17.08  2520000


             Date         Open         High          Low        Close  \
19121  2026-01-05  6892.189941  6920.379883  6891.560059  6902.049805
19122  2026-01-06  6908.029785  6948.689941  6904.020020  6944.819824
19123  2026-01-07  6945.069824  6965.689941  6919.189941  6920.930176
19124  2026-01-08  6914.109863  6931.279785  6899.330078  6921.459961
19125  2026-01-09  6927.830078  6978.359863  6917.640137  6966.279785

         Adj Close      Volume
19121  6902.049805  5771930000
19122  6944.819824  5509680000
19123  6920.930176  5214480000
19124  6921.459961  5333200000
19125  6966.279785  5163900000




/kaggle/working/Cleaned_RELIANCE.NS_Max.csv
         Date      Open      High       Low     Close  Adj Close     Volume
0  1995-12-31  7.319124  7.358397  7.270925  7.345901   4.617048  104121369
1  1996-01-01  7.328050  7.363753  7.235222  7.288776   4.581145  168743308
2  1996-01-02  7.408381  7.745775  7.328050  7.344116   4.615928  209323879
3  1996-01-03  7.274495  7.297702  7.178097  7.276280   4.573291  216900264
4  1996-01-04  7.247718  7.247718  7.163816  7.226296   4.541874  166708467


            Date    Open         High          Low        Close    Adj Close  \
7416  2026-01-04  1593.0  1611.800049  1575.300049  1578.099976  1578.099976
7417  2026-01-05  1569.0  1569.000000  1496.300049  1507.599976  1507.599976
7418  2026-01-06  1510.0  1520.000000  1498.000000  1504.199951  1504.199951
7419  2026-01-07  1500.0  1503.900024  1468.800049  1470.599976  1470.599976
7420  2026-01-08  1465.0  1479.900024  1465.000000  1475.300049  1475.300049

        Volume
7416   8704973
7417  27417125
7418  11199340
7419  16518684
7420   8335311




/kaggle/working/Cleaned_BSESN_Max.csv
         Date         Open         High          Low        Close  \
0  2003-07-13  3704.629883  3726.560059  3704.629883  3720.750000
1  2003-07-14  3719.169922  3733.879883  3657.179932  3686.340088
2  2003-07-15  3702.139893  3729.020020  3662.699951  3721.649902
3  2003-07-16  3728.840088  3750.000000  3660.340088  3668.909912
4  2003-07-17  3651.389893  3684.229980  3625.729980  3647.580078

     Adj Close  Volume
0  3720.750000   21200
1  3686.340088   22800
2  3721.649902   18400
3  3668.909912   22000
4  3647.580078   22000


            Date          Open          High           Low         Close  \
5526  2026-01-04  85640.046875  85883.500000  85315.328125  85439.617188
5527  2026-01-05  85331.140625  85397.781250  84900.101562  85063.343750
5528  2026-01-06  84620.398438  85075.992188  84617.492188  84961.140625
5529  2026-01-07  84778.023438  84965.273438  84110.101562  84180.960938
5530  2026-01-08  84022.093750  84406.218750  83402.281250  83576.242188

         Adj Close  Volume
5526  85439.617188   12600
5527  85063.343750   23300
5528  84961.140625   19200
5529  84180.960938   26300
5530  83576.242188   12500




/kaggle/working/Cleaned_RUT_Max.csv
         Date        Open        High         Low       Close   Adj Close  \
0  1987-09-10  167.440002  168.979996  167.440002  168.970001  168.970001
1  1987-09-11  168.970001  170.539993  168.750000  170.539993  170.539993
2  1987-09-14  170.529999  170.949997  170.149994  170.429993  170.429993
3  1987-09-15  170.419998  170.440002  169.130005  169.199997  169.199997
4  1987-09-16  169.309998  170.029999  168.820007  168.919998  168.919998

      Volume
0  179800000
1  178000000
2  154400000
3  136200000
4  195700000


            Date         Open         High          Low        Close  \
9649  2026-01-05  2516.810059  2556.239990  2516.810059  2547.919922
9650  2026-01-06  2544.959961  2582.989990  2541.629883  2582.899902
9651  2026-01-07  2585.620117  2585.620117  2563.399902  2575.419922
9652  2026-01-08  2567.610107  2608.580078  2566.659912  2603.909912
9653  2026-01-09  2614.729980  2635.800049  2606.659912  2624.219971

        Adj Close      Volume
9649  2547.919922  5771930000
9650  2582.899902  5509680000
9651  2575.419922  5214480000
9652  2603.909912  5333200000
9653  2624.219971  5163900000




/kaggle/working/Cleaned_IXIC_Max.csv
         Date        Open        High         Low       Close   Adj Close  \
0  1984-10-11  244.199997  244.699997  244.199997  244.699997  244.699997
1  1984-10-12  245.500000  246.199997  245.500000  246.199997  246.199997
2  1984-10-15  246.800003  247.699997  246.800003  247.699997  247.699997
3  1984-10-16  247.800003  247.899994  247.100006  247.300003  247.300003
4  1984-10-17  247.100006  247.100006  246.800003  247.100006  247.100006

     Volume
0  62860000
1  58860000
2  61820000
3  57440000
4  64670000


             Date          Open          High           Low         Close  \
10387  2026-01-05  23449.669922  23476.509766  23332.230469  23395.820312
10388  2026-01-06  23446.960938  23559.150391  23389.570312  23547.169922
10389  2026-01-07  23544.890625  23723.369141  23504.210938  23584.279297
10390  2026-01-08  23548.880859  23558.169922  23353.460938  23480.019531
10391  2026-01-09  23496.210938  23721.150391  23426.480469  23671.349609

          Adj Close      Volume
10387  23395.820312  8737320000
10388  23547.169922  9012640000
10389  23584.279297  8396920000
10390  23480.019531  7723140000
10391  23671.349609  8124420000

In [9]:
!rm /kaggle/working/Cleaned_NSEI_Max.csv

In [10]:
nsei=pd.read_csv('/kaggle/input/data-historical/NSEI_MAX.csv')
nsei.head(5)

,date,close,open,high,low,volume
0,2007-09-17T00:00:00+05:30,4494.649902,4518.450195,4549.049805,4482.850098,0.0
1,2007-09-18T00:00:00+05:30,4546.200195,4494.100098,4551.799805,4481.549805,0.0
2,2007-09-19T00:00:00+05:30,4732.350098,4550.250000,4739.000000,4550.250000,0.0
3,2007-09-20T00:00:00+05:30,4747.549805,4734.850098,4760.850098,4721.149902,0.0
4,2007-09-21T00:00:00+05:30,4837.549805,4752.950195,4855.700195,4733.700195,0.0

In [11]:
nsei.shape

(4520, 6)

In [12]:
files_to_change_data=glob.glob('/kaggle/input/data-historical/*')

for i in files_to_change_data:
    df=pd.read_csv(i)
    print(i)
    cols_to_drop=['Dividends','Stock Splits']
    existing_cols=[j for j in cols_to_drop if j in df.columns]

    if existing_cols:
        df.drop(columns=cols_to_drop,inplace=True)
    print(df.columns)
    print(df.shape)

    df.dropna(inplace=True)
    print(df.shape)
    
    if 'date' in df.columns:
        df['date']=pd.to_datetime(df['date'],utc=True)
        df['date']=df['date'].dt.date
        
    filename = os.path.basename(i)
    save_path = f"/kaggle/working/Cleaned_{filename}"
    
    df.to_csv(save_path, index=False)

/kaggle/input/data-historical/HDFCBANK.NS_MAX_NSE.csv
Index(['date', 'close', 'open', 'high', 'low', 'volume'], dtype='object')
(7885, 6)
(7885, 6)
/kaggle/input/data-historical/NSEI_MAX.csv
Index(['date', 'close', 'open', 'high', 'low', 'volume'], dtype='object')
(4520, 6)
(4520, 6)

In [13]:
files_to_see=['/kaggle/working/Cleaned_HDFCBANK.NS_MAX_NSE.csv','/kaggle/working/Cleaned_NSEI_MAX.csv']

for i in files_to_see:
    df=pd.read_csv(i)
    print(i)
    print(df.head(5))
    print('\n')
    print(df.tail(5))
    print('\n')
    print('\n')

/kaggle/working/Cleaned_HDFCBANK.NS_MAX_NSE.csv
         date  close  open  high   low     volume
0  1995-06-14   2.27  2.30  2.30  2.25  2070000.0
1  1995-06-15   2.26  2.28  2.31  2.25  4246000.0
2  1995-06-18   2.26  2.26  2.27  2.22  1798000.0
3  1995-06-19   2.25  2.26  2.26  2.24  2792000.0
4  1995-06-20   2.27  2.33  2.33  2.27  1182000.0


            date   close     open     high    low      volume
7880  2026-01-04  977.50  1005.75  1006.40  976.3  27647379.0
7881  2026-01-05  962.20   962.70   966.70  956.0  31988783.0
7882  2026-01-06  949.05   956.00   956.45  946.0  52884712.0
7883  2026-01-07  946.70   944.70   953.00  941.4  21928849.0
7884  2026-01-08  939.00   945.00   950.60  933.3  38183685.0




/kaggle/working/Cleaned_NSEI_MAX.csv
         date        close         open         high          low  volume
0  2007-09-16  4494.649902  4518.450195  4549.049805  4482.850098     0.0
1  2007-09-17  4546.200195  4494.100098  4551.799805  4481.549805     0.0
2  2007-09-18  4732.350098  4550.250000  4739.000000  4550.250000     0.0
3  2007-09-19  4747.549805  4734.850098  4760.850098  4721.149902     0.0
4  2007-09-20  4837.549805  4752.950195  4855.700195  4733.700195     0.0


            date     close     open      high       low       volume
4515  2026-01-04  26250.30  26333.7  26373.20  26210.05  338777649.0
4516  2026-01-05  26178.70  26189.7  26273.95  26124.75  383040203.0
4517  2026-01-06  26140.75  26143.1  26187.15  26067.90  338216740.0
4518  2026-01-07  25876.85  26106.5  26133.20  25858.45  328520950.0
4519  2026-01-08  25683.30  25840.4  25940.60  25623.00  348745661.0

In [14]:
import zipfile

files_to_zip=glob.glob('/kaggle/working/C*')

output_file_name='Cleaned-Historical-Data.zip'

with zipfile.ZipFile(output_file_name,'w',zipfile.ZIP_DEFLATED) as zipf:
    for file in files_to_zip:
        zipf.write(file)

print('Job Done')

Job Done