In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
hdfc=pd.read_csv('/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_HDFC.csv')

In [4]:
hdfc.head(5)

,Date,Title,Description,Link,Publisher
0,2021-01-06 08:00:00,HDFC Bank reports double-digit increase in dep...,HDFC Bank reports double-digit increase in dep...,https://news.google.com/rss/articles/CBMiogFBV...,Elets BFSI
1,2021-01-08 08:00:00,In case you missed it | HDFC-HDFC Bank merger:...,In case you missed it | HDFC-HDFC Bank merger:...,https://news.google.com/rss/articles/CBMi6AFBV...,Moneycontrol
2,2021-01-07 08:00:00,Digital transformation in banking: author Tama...,Digital transformation in banking: author Tama...,https://news.google.com/rss/articles/CBMigwFBV...,YourStory.com
3,2021-01-08 08:00:00,Former HDFC Bank Managing Director Aditya Puri...,Former HDFC Bank Managing Director Aditya Puri...,https://news.google.com/rss/articles/CBMi1AFBV...,Business Standard
4,2021-01-06 08:00:00,HDFC Bank's advances grew 16% in December quar...,HDFC Bank's advances grew 16% in December quar...,https://news.google.com/rss/articles/CBMilwFBV...,The Hans India

In [5]:
hdfc.tail(5)

,Date,Title,Description,Link,Publisher
10757,2026-01-09 14:56:02,5 Cashback Credit Cards in India for Everyday ...,5 Cashback Credit Cards in India for Everyday ...,https://news.google.com/rss/articles/CBMilwFBV...,Trade Brains
10758,2026-01-10 06:07:00,"SBI ATM fee hike explained: Savings, salary ac...","SBI ATM fee hike explained: Savings, salary ac...",https://news.google.com/rss/articles/CBMi_gFBV...,The Economic Times
10759,2026-01-09 09:54:00,Senior Citizen FD Investment: Can you pay zero...,Senior Citizen FD Investment: Can you pay zero...,https://news.google.com/rss/articles/CBMiiAJBV...,The Economic Times
10760,2026-01-09 09:19:34,"HDFC Bank Trims Key Lending Rates, MCLR Cut Of...","HDFC Bank Trims Key Lending Rates, MCLR Cut Of...",https://news.google.com/rss/articles/CBMiwgFBV...,Free Press Journal
10761,2026-01-10 05:29:13,"Top Q3 results next week: TCS, HCL Technologie...","Top Q3 results next week: TCS, HCL Technologie...",https://news.google.com/rss/articles/CBMikAJBV...,Business Upturn

In [6]:
hdfc['Publisher'].unique()

array(['Elets BFSI', 'Moneycontrol', 'YourStory.com', 'Business Standard',
       'The Hans India', 'Live From A Lounge', 'Express Pharma',
       'Healthcare Radius', 'People Matters - HR News', 'livemint.com',
       'Business Today', 'News18', 'mckinsey.com', 'Moneylife', 'Taxscan',
       'Times of India', 'Zee Business', 'India Today', 'The Hindu',
       'The News Minute', 'The Indian Express', 'Hindustan Times',
       'Times Now', 'CNBC TV18', 'The Financial Express', 'Goodreturns',
       'DT Next', 'AffairsCloud.com', 'Inshorts', 'Scroll.in',
       'The New Indian Express', 'Pune Mirror', 'The CSR Universe',
       'The Economic Times', 'Retail Banker International', 'MediaNama',
       'Telangana Today', 'Techcircle', 'India TV News', 'Nenow.in',
       'The Shorty Awards', 'Mediabrief.com', 'Banking Frontiers',
       'thehitavada.com', 'DNA India', 'PulauJudi', 'Cafemutual',
       'Times Internet', 'Upstox', 'Trade Brains', 'Greater Kashmir',
       'Kashmir Life', 'Kashmir Observer', 'inventiva.co.in',
       'Exchange4Media', 'ANI News', 'Jagoinvestor',
       'The Kashmir Horizon', 'ET Telecom', 'SCC Online', 'india.com',
       'FoneArena.com', 'FACTLY', 'BOOM Fact Check', 'freefincal',
       'Gulf News', 'ETHRWorld.com', 'Daily FT', 'Express Computer',
       'ATM Marketplace', 'Equitypandit', 'Marcellus', 'IBTimes India',
       'varindia.com', 'Deccan Herald', 'Adda247', 'NDTV Profit', 'Inc42',
       'Adgully.com', 'HT Tech', 'investor academy', 'Equitymaster',
       'Social News XYZ', 'eFinancialCareers', 'getmoneyrich',
       'Yahoo Finance', 'Ahmedabad Mirror', 'NewsBytes', 'ThePrint',
       'Cityairnews', 'CoinGape', 'BusinessLine', 'Zee News',
       'TyN Magazine', 'Mashable India', 'Campaign Asia', 'Gadgets 360',
       'Swarajyamag', 'Passionate In Marketing', 'HR Katha',
       'Startup Story', 'Forbes India', 'Business Wire India',
       'Yahoo Finance Singapore', 'Tathya', 'Indian PSU', 'The Quint',
       'informalnewz', 'Business Wire', 'TheBanker.com',
       'Mobility Outlook', 'Reuters', 'Bloomberg.com',
       'Morningstar India', 'Investing.com India', 'India CSR', 'WION',
       'ABP Live English', 'Oneindia', 'AajTak', 'Invest Yadnya',
       'Krishi Jagran', 'TechStory', 'PersonalFN', 'Groww', 'theweek.in',
       'newsd.in', 'Invest India', 'ET EnergyWorld', 'MarketSmith India',
       'Euromoney', 'The Morning Context', 'ET Retail', 'Gulf Times',
       'Telegraph India', 'The Asian Age', 'AI Magazine', 'Outlook India',
       'TechCrunch', 'tennews.in', 'PSU Connect', 'PGurus', 'digit.in',
       'Indiatimes', 'EVO India', 'Punekar News',
       'Global Finance Magazine', 'PR Newswire', 'Deccan Chronicle',
       'Agriculture Post', 'Techthirsty', 'ET BrandEquity',
       'Global Prime News', 'SAG Infotech Official Tax Blog',
       'Fortune India', 'indiaherald.com', 'Forbes', 'KalingaTV',
       'Arunachal24', 'Finshots', 'The Ken', 'India Infoline',
       'APAC Media', 'Udaipur Kiran', 'Jagran Josh', 'ClearTax',
       'orissapost.com', 'Punjab News Express', 'Medical Dialogues',
       'Digital First Magazine', 'Barak Bulletin', 'Siasat.com',
       'Daijiworld', 'Private Banker International', 'Pressnote.in',
       'Live Law', 'Gulf Business', 'Realty Plus Magazine',
       'Medical Buyer', 'IBS Intelligence', 'The Hills Times',
       'BW People', 'prmoment.in', 'gadgetbridge.com', 'ET Infra',
       'How2shout', 'S&P Global', 'banking-gateway.com', 'Value Research',
       'newsclick.in', 'qz.com', 'dailyo.in', 'TheWire.in', 'afaqs!',
       'Bar and Bench', 'outlookbusiness.com', 'EastMojo',
       'The Motley Fool', 'The Daily Star', 'MillenniumPost',
       'The Economist', 'Governance Now', 'Maps of India',
       'ClearTax Chronicles', 'Liquide Blog', 'Tribune India',
       'sunpost.in', 'Tech Observer Magazine', 'ET Auto', 'IFLR',
       'zoomnews.in', 'inkl', 'PIB', 'Alt News', 'BankersAdda',
       'Accenture', 'Football Counter', 'ledgerinsights.com',
       'Entrepreneur', 'Daily Excelsior', 'LatestLY', 'VCCircle',
       'Times of Oman', 'ZAWYA', 'Arab News', 'Face2News',
       'Daily Mirror - Sri Lanka', 'BizzBuzz', 'KNN India',
       'India Book of Records', 'Campaign India', 'StoryBoard 18',
       'The420.in', 'Life Insurance International', 'Sakshi Education',
       'India Today NE', 'capitalmonitor.ai', 'Housing', 'MediaNews4U',
       'ETLegalWorld.com', 'smartprix.com', 'Verdictum', 'Gaadiwaadi.com',
       'MorungExpress', 'global-agriculture.com', 'Firstpost',
       'Brighter Kashmir', 'defencewatch.in', 'Outlook Money', 'CaseMine',
       'KNS Kashmir', 'Entrackr', 'Analytics India Magazine',
       'Tata Motors', 'ZebPay', 'The Finance Story', 'YouGov',
       'This Week India', 'Staff News', 'The CSR Journal',
       'Microsoft Source', 'MSDynamicsWorld.com', 'Studycafe',
       'Free Press Journal', 'iTnews Asia', 'The Island.lk',
       'news24online.com', 'Enterprise Apps Today', 'Qatar Tribune',
       'TelecomTalk', 'invesco.com', 'CEO Insights Asia',
       'curlytales.com', 'Business Outreach Magazine',
       'Myinvestmentideas', 'World Business Outlook',
       'Bank Info Security', 'Mumbai Live', 'Bitdefender',
       'english.factcrescendo.com', 'Trak.in', 'CarWale',
       'Frontier Enterprise', 'India Retailing', 'Vajiram & Ravi',
       'TechGraph', 'Indian Cooperative', 'Careers360', 'CryptoRank',
       'cio.com', 'HDFC Sky', 'Seeking Alpha', 'Kashmir Despatch',
       'Indian Startup News', 'Construction Week India', 'Media4Growth',
       'Business Upturn', 'ICICI Direct', 'Indiablooms',
       'The Sunday Guardian', 'NDTV', 'CXOToday.com', 'FinTech Global',
       'APNLive', 'News9live', 'TradingView — Track All Markets',
       'Business Model Analyst', 'wirally.com', 'ACKO Drive',
       'Observer Voice', 'PTC News', 'marketfeed', 'Onmanorama', 'ET Now',
       'Editorji', 'CNBC', 'Capitalmind', 'Social Samosa',
       'Sarkaritel.com', 'thenationalnews.com', 'LawBeat',
       'Financial Times', 'thecore.in', 'Ommcom News', 'APN News',
       'Down To Earth', 'Bilkul Online', 'Magzter',
       'Autocar Professional', 'Construction World', 'The Statesman',
       'ET Realty', 'Asia Insurance Review', 'Mongabay-India',
       'Hotelier India', 'Asian Mail', 'Dazeinfo', 'LoyaltyLobby',
       'BW Businessworld', 'Gadgets To Use', 'Forrester', 'TimelineDaily',
       'BW Marketing World', 'Metro Rail News',
       'Telangana NavaNirmana Sena', 'bestmediainfo.com',
       'Investing.com Australia', 'Physics Wallah', 'PSU Watch',
       'Asian Banking & Finance', 'MyNation', 'Business Review Live',
       'Agency Reporter', 'KIIT', 'Republic World', 'The Blunt Times',
       'V3Cars', 'fintechbiznews.com', 'CricketGraph',
       'Times Now Navbharat', 'top10stockbroker.com', 'MarketWatch',
       'The Business Times', 'Dataconomy', 'Hubbis', 'The Law Advice',
       'SMEStreet', 'newsdrum.in', 'Little Black Book | LBBOnline',
       'Mercomindia.com', 'GQ India', 'InvestorPlace',
       'businessleague.in', 'Law Trend', 'Garhwal Post', 'Shiksha.com',
       'Newschecker', 'World Bank Blogs', 'UnlistedZone',
       'HDFC ERGO General Insurance', 'UNITED NEWS OF INDIA',
       'The Globe and Mail', 'CTV News', 'National Post',
       'Condé Nast Traveller India', 'CIC News', 'Dainik Bhaskar',
       'HT Auto', 'AFR', 'MensXP', 'KED Global',
       'TradingView – Tüm Piyasaları Takip Edin', 'The Korea Times',
       'The Korea Herald', 'PUNE PULSE', 'MYLAPORE TIMES -',
       'SportsMint Media', 'FinanceAsia', 'Utkarsh Classes',
       'Nikkei Asia', 'Techlusive', 'SolarQuarter', 'Indian Masterminds',
       'International Finance Corporation (IFC)', 'BW Legal World',
       'Cyril Amarchand Mangaldas', 'Airtel', 'Newsband',
       'madhyamamonline.com', 'Prop News Time', 'Deadant',
       'The Avenue Mail', 'IMPACT Magazine', 'MarketScreener',
       'Private Equity Insights', 'ET Education',
       'The Daily Brief by Zerodha',
       'Northeast News - Northeast India news 24×7 -', 'IPO Watch',
       'BW Education', 'Siliconindia', 'Fortune', 'The Live Nagpur',
       'INsauga', 'Timesbull', 'Investing.com UK', 'Nicobar Times',
       'Finovate', 'FinanceFeeds', 'ET Edge Insights', 'bobsguide.com',
       'Borok Times', 'ETV Bharat', 'LawChakra', 'thefederal.com',
       'The Bridge Chronicle', 'Vartha Bharati', 'Tractor Junction',
       'Gizmochina', 'Moneyexcel', 'Binance', 'dailynews.lk',
       'The Asian Banker', 'Energetica India Magazine', 'Rediff MoneyWiz',
       'bernama', 'startupguys.net', 'LinkedIn', 'Hub News',
       'policycircle.org', 'Clarion India', 'IBC24.in', 'GK Today',
       'Capital Market', 'Nasdaq', 'Analytics Insight', 'MarketsMojo',
       'Samco', 'DriveSpark', 'The Logical Indian', 'Medium', 'OpIndia',
       'Disruption Banking', 'Thekanal', 'The News Agency',
       'News Riveting', 'The Goan', 'The Realty Today',
       'pv magazine India', 'convergence-now.com', 'Marketing91',
       'Indianweb2.com', 'MarcaMoney', 'Asianet Newsable', 'Sarkari Exam',
       'topnews.in', 'Rewa Riyasat', 'facebook.com', 'Odisha TV',
       'domain-b.com', 'MSN', 'EventFAQs', 'Informist Media',
       'Babushahi.com', 'TravelBiz Monitor', 'GujaratSamachar English',
       'Press Trust of India', 'Bhaskar English', 'The INS News',
       'Northeast Today', 'tripuratimes.com', 'Patrika News',
       'Indian Television Dot Com', 'City Today News',
       'Business Strategy Hub', 'Brand Finance', 'True Scoop',
       'Insolvency Tracker', 'QA Financial', "Investor's Business Daily",
       'First India', 'Highland Post', 'PressReader', 'Lawyer E News',
       'IndiaLaw LLP', 'Tripura Chronicle', 'Hunt Scanlon Media',
       'Influencer Marketing Hub', 'IPO Central', 'Herzindagi',
       'Bessemer Venture Partners', '| Asian Legal Business', 'AppAdvice',
       'The Financial World', 'TradingView - Alle Märkte im Blick',
       'Zacks Investment Research', 'Citywire', 'blog.google',
       'Branding in Asia', 'Career Power', 'Adobe', 'scanx.trade',
       'coastaldigest.com', 'Tech in Asia', 'globaldata.com',
       'pragativadi.com', 'TipRanks', 'Klover.ai', 'India News Network',
       'Investing.com', 'Law.asia', 'Stellantis Media', 'GaadiKey',
       'Asset Publishing and Research', 'VinFast India', 'TNGlobal',
       'Manufacturing Today India', 'Entrepreneur India', 'IANS LIVE',
       'Motoroids', 'Dalal Street Investment Journal',
       'thekashmiriyat.co.uk', 'JLL', 'himachalpr.gov.in', 'ciol.com',
       'Veloxx media', 'NewsMeter', 'Exla Resources',
       'shareprice-target.com', 'MarketBeat', 'BBC', 'newskarnataka.com',
       'Coinfomania', 'Udayavani', 'IBC World News', 'The Sen Times',
       'Mathrubhumi English', 'lokmattimes.com', 'SSBCrack',
       'Shop SSBCrack', 'expressnews.asia', 'News Arena India', 'Meyka',
       'Syllad', 'The Meghalayan Express', 'EquityBulls', 'simplywall.st',
       'Stocktwits', 'Whalesbook', 'Smartkarma', 'Legal Parivar',
       'Raw Law', 'Khaleej Times', 'Business Remedies', 'Eastern Mirror',
       'The Arc - Technology, Startups, Entrepreneurship News & Analysis',
       'The Times of India', 'Sahm', 'prameyanews.com', 'english.vov.vn',
       'EconomyNext', 'Kantar', 'manifest-media.in', 'G Plus News',
       'Statista', 'Wipro', 'CXO Digitalpulse', 'InvestyWise',
       'TechStock²', 'Devdiscourse', 'Travel And Tour World', 'NewsX',
       'Bharat Speaks', 'bollywoodhelpline.com', 'AD HOC NEWS', '富途牛牛',
       'Cricket Duniya -'], dtype=object)

In [7]:
import glob
import os

files_to_change_data=glob.glob('/kaggle/input/news-data/Weekly_data/*')

for i in files_to_change_data:
    df=pd.read_csv(i)
    print(i)
    cols_to_drop=['Description','Publisher','Link']
    existing_cols=[j for j in cols_to_drop if j in df.columns]

    if existing_cols:
        df.drop(columns=cols_to_drop,inplace=True)
    print(df.columns)
    print(df.shape)

    df.dropna(inplace=True)
    print(df.shape)
    
    if 'Date' in df.columns:
        df['Date']=pd.to_datetime(df['Date'],utc=True)
        df['Date']=df['Date'].dt.date
        
    filename = os.path.basename(i)
    save_path = f"/kaggle/working/Cleaned_{filename}"
    
    df.to_csv(save_path, index=False)

/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_RUT.csv
Index(['Date', 'Title'], dtype='object')
(4829, 2)
(4829, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_NASDAQ.csv
Index(['Date', 'Title'], dtype='object')
(8647, 2)
(8647, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_SENSEX.csv
Index(['Date', 'Title'], dtype='object')
(10960, 2)
(10960, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_SPX.csv
Index(['Date', 'Title'], dtype='object')
(133, 2)
(133, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_NIFTY.csv
Index(['Date', 'Title'], dtype='object')
(9716, 2)
(9716, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_RELIANCE.csv
Index(['Date', 'Title'], dtype='object')
(12183, 2)
(12183, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_MARKET.csv
Index(['Date', 'Title'], dtype='object')
(13052, 2)
(13052, 2)
/kaggle/input/news-data/Weekly_data/WEEKLY_DATA_HDFC.csv
Index(['Date', 'Title'], dtype='object')
(10762, 2)
(10762, 2)

In [8]:
files_to_see=glob.glob('/kaggle/working/*')

for i in files_to_see:
    df=pd.read_csv(i)
    print(i)
    print(df.head(5))
    print('\n')
    print(df.tail(5))
    print('\n')
    print('\n')

/kaggle/working/Cleaned_WEEKLY_DATA_NIFTY.csv
         Date                                              Title
0  2021-01-07  D-St on a high! 48 out of 50 Nifty stocks abov...
1  2021-01-01  Sensex, Nifty end at record high on first day ...
2  2021-01-01           Market recap for 1 January 2021 - Upstox
3  2021-01-06  Short term view in NIFTY50 for INTRADAY - Mone...
4  2021-01-08  Sensex ends at fresh closing peak of 48,782, u...


            Date                                              Title
9711  2026-01-09  Sensex slumps 651 pts; consumer durables share...
9712  2026-01-09  Today's Stock Market Update: Discover the Top ...
9713  2026-01-09  Stock market crash today: BEARS maul bulls as ...
9714  2026-01-09  Nifty 50 top gainers today, January 9: Asian P...
9715  2026-01-09  Nifty 50 top losers today, January 9: Adani En...




/kaggle/working/Cleaned_WEEKLY_DATA_SPX.csv
         Date                                              Title
0  2026-01-11  Arbitration | Lack Of S. 21 Notice Not Fatal I...
1  2026-01-11  No Rahul-Stalin in Tamil Nadu? DMK rejects Con...
2  2026-01-10  Parents on RFK Jr.’s advice on sweets: ‘Comple...
3  2026-01-10  FBI’s Inquiry Into Minneapolis ICE Shooting Fa...
4  2026-01-08  Why Indias Overreliance on Russian S-400 Missi...


           Date                                              Title
128  2026-01-11  U.K.'s former ambassador to U.S. apologizes to...
129  2026-01-11  Liverpool's Bradley out for season with knee i...
130  2026-01-09  ‘JD(S)-BJP will win 150 seats’: Nikhil Kumaras...
131  2026-01-08  Obituary information for Dr. Henry S. Jordan -...
132  2026-01-10  Arms consignment dropped by drone seized near ...




/kaggle/working/Cleaned_WEEKLY_DATA_NASDAQ.csv
         Date                                              Title
0  2021-01-03  Stocks begin 2021 with a sell-off, Dow drops m...
1  2021-01-04          2020 Review and Outlook for 2021 - Nasdaq
2  2021-01-02  These are the best-performing Nasdaq and S&P 5...
3  2021-01-01  The biggest market winners and losers of 2020,...
4  2021-01-06  US STOCKS Dow, S&P 500 close higher, but pro-T...


            Date                                              Title
8642  2026-01-10  Will Quad Graphics Inc. stock outperform Nasda...
8643  2026-01-09  Income stock beat Nasdaq index returns - July ...
8644  2026-01-09  Dow Hits a Record High After December Jobs Rep...
8645  2026-01-09  Nasdaq Composite stalls below 23,480 after tec...
8646  2026-01-09  7,238 Shares in Fidelity NASDAQ Composite Inde...




/kaggle/working/Cleaned_WEEKLY_DATA_SENSEX.csv
         Date                                              Title
0  2021-01-01  Sensex rises 118 points to settle at fresh clo...
1  2021-01-04  Sensex ends 308 pts up at 48,177, Nifty at 14,...
2  2021-01-05  Closing Bell: Nifty ends at 14,200, Sensex gai...
3  2021-01-01  Sensex, Nifty end at record high on first day ...
4  2021-01-08  Sensex ends at fresh closing peak of 48,782, u...


             Date                                              Title
10955  2026-01-10  Sensex and Nifty Decline Over 2% in Five Sessi...
10956  2026-01-09  Sensex slumps 651 pts; consumer durables share...
10957  2026-01-09  Dalal Streets End Lower, Sensex Ended Above 83...
10958  2026-01-09  Tariff jitters extend selloff; Sensex drops 60...
10959  2026-01-09  Sensex wipes off ₹13.5 lakh crore from investo...




/kaggle/working/Cleaned_WEEKLY_DATA_MARKET.csv
         Date                                              Title
0  2021-01-07  2020 was a rollercoaster year for Indian stock...
1  2021-01-05  Closing Bell: Nifty ends at 14,200, Sensex gai...
2  2021-01-04  India’s market cap swells to $2.5 trillion - l...
3  2021-01-04  Sensex ends 308 pts up at 48,177, Nifty at 14,...
4  2021-01-01  Sensex rises 118 points to settle at fresh clo...


             Date                                              Title
13047  2026-01-09  NSE, BSE to hold mock trading session on Satur...
13048  2026-01-10  3M India: Stock to Postit in a portfolio - IPO...
13049  2026-01-09  India Stocks Fall at Close; Nifty 50 Drops 0.7...
13050  2026-01-09  Closing Bell: Sensex slumps 605 pts, Nifty bel...
13051  2026-01-09  India stock market today: Nifty, Sensex end lo...




/kaggle/working/Cleaned_WEEKLY_DATA_HDFC.csv
         Date                                              Title
0  2021-01-06  HDFC Bank reports double-digit increase in dep...
1  2021-01-08  In case you missed it | HDFC-HDFC Bank merger:...
2  2021-01-07  Digital transformation in banking: author Tama...
3  2021-01-08  Former HDFC Bank Managing Director Aditya Puri...
4  2021-01-06  HDFC Bank's advances grew 16% in December quar...


             Date                                              Title
10757  2026-01-09  5 Cashback Credit Cards in India for Everyday ...
10758  2026-01-10  SBI ATM fee hike explained: Savings, salary ac...
10759  2026-01-09  Senior Citizen FD Investment: Can you pay zero...
10760  2026-01-09  HDFC Bank Trims Key Lending Rates, MCLR Cut Of...
10761  2026-01-10  Top Q3 results next week: TCS, HCL Technologie...




/kaggle/working/Cleaned_WEEKLY_DATA_RELIANCE.csv
         Date                                              Title
0  2021-01-01  India's Reliance Industries and chairman fined...
1  2021-01-01  Reliance Petroleum case | SEBI fines Reliance ...
2  2021-01-04  IMG offloads 50% stake in Indian JV to Relianc...
3  2021-01-02  SEBI Imposes Rs70 Crore Penalty on Reliance In...
4  2021-01-04  Reliance says no plans to enter contract farmi...


             Date                                              Title
12178  2026-01-09  India’s Reliance in talks for US permit to buy...
12179  2026-01-09  Investors Hope for Bounce in Reliance Industri...
12180  2026-01-10  Reliance’s Venezuela Oil Gambit: Could This Mo...
12181  2026-01-10  Top Q3 results next week: TCS, HCL Technologie...
12182  2026-01-09  Energy sector stocks today: Oil India jumps 2....




/kaggle/working/Cleaned_WEEKLY_DATA_RUT.csv
         Date                                              Title
0  2021-01-01  How Every Asset Class, Currency, and S&P 500 S...
1  2021-01-01  Five Investment Trends That Skyrocketed in 202...
2  2021-01-05  Updating My Favorite Performance Chart For 202...
3  2021-01-04  2021's Alarm Goes Off for Market Indexes - Yah...
4  2021-01-08  Blacklisted Chinese Telecoms Carriers Cut From...


            Date                                              Title
4824  2026-01-09  Apartment Investment and Management Company (A...
4825  2026-01-09  United Natural Foods (UNFI) Faced a Cyber Atta...
4826  2026-01-09  Russell 2000 Breakout Revives XRP Correlation ...
4827  2026-01-09  The Altseason Signal Traders Wait For Is Now A...
4828  2026-01-09  Stock Market Today: S&P 500 (SPX) 6,939, Dow (...

In [9]:
import zipfile

files_to_zip=glob.glob('/kaggle/working/C*')

output_file_name='Cleaned-News-Data.zip'

with zipfile.ZipFile(output_file_name,'w',zipfile.ZIP_DEFLATED) as zipf:
    for file in files_to_zip:
        zipf.write(file)

print('Job Done')

Job Done